id: A207E0442
title: 'A Drop of Moonlight: A Guru Yoga for Lord Mila'
type: translation
pechas:
- I43F6461F
- I260CFDBE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:02:03.816330
  last_modified_at: 2023-01-04 13:02:03.816339
  collections:
  - Milarepa Series
  - Works of Tibetan Masters
alignment_to_base:
  I43F6461F/C43A: AC0D
  I260CFDBE/B4AE: AC0D
